### ISSUE TITLE
0.19 upgrade

### ISSUE THREAD

**Issue by lukewestby** [Zinggi/elm-random-pcg-extended#1]
Hey @Zinggi,

NoRedInk is going to fork this and Zinggi/elm-uuid and publish them for 0.19 so we can finish up our codebase upgrade. Would you like us to also send you pull requests so you can publish your own?

**Comment by Zinggi** [comment]
Hey @lukewestby,

Yeah, that would be great! I unfortunately never had the time to do the upgrade myself, but if you could send me a PR, that would be sweet 😄 

Thanks a lot!

**Comment by ZimbiX** [comment]
I've just had quite an adventure figuring out which UUID library/fork to use for proper randomness.

I guess they forgot to submit a PR, but the work is here:

https://github.com/NoRedInk/elm-uuid
https://github.com/NoRedInk/elm-random-pcg-extended
https://github.com/NoRedInk/elm-random-general

I'm going to use the [`NoRedInk/elm-uuid`](https://package.elm-lang.org/packages/NoRedInk/elm-uuid/2.0.0/) package until your packages are updated from theirs =)

**Comment by Zinggi** [comment]
Yeah, sorry about that. I still follow what happens in Elm land, but I'm not using it anywhere in production so I don't have any motivation and energy to maintain a package I'm not even using myself.

I think at this point it makes sense to just link to the NoRedInk fork from here, even if they just link back...
